### ISSUE TITLE
python tests fail

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/Magics-rpm#1]
Tests are temporarily disabled in the specfile, since every python test fails like this:

```
+ MAGPLUS_HOME=/home/makerpm/rpmbuild/BUILDROOT/Magics-3.0.3-1.el7.centos.x86_64
+ CTEST_OUTPUT_ON_FAILURE=1
+ ctest
Test project /home/makerpm/rpmbuild/BUILD/Magics-3.0.3-Source/build
    Start 1: basic_c
1/9 Test #1: basic_c ..........................   Passed    0.11 sec
    Start 2: basic_python
2/9 Test #2: basic_python .....................***Failed    0.29 sec
Traceback (most recent call last):
  File "coast.py", line 11, in <module>
    from Magics.macro import *
  File "/home/makerpm/rpmbuild/BUILD/Magics-3.0.3-Source/build/python/Magics/macro.py", line 12, in <module>
    from . import Magics
  File "/home/makerpm/rpmbuild/BUILD/Magics-3.0.3-Source/build/python/Magics/Magics.py", line 25, in <module>
    dll  = ctypes.CDLL(lib)
  File "/usr/lib64/python3.4/ctypes/__init__.py", line 346, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libMagPlus.so: cannot open shared object file: No such file or directory
```

and `Magics.py` has this funny way of assigning the lib:
```
if lib is None:
    lib = "/usr/lib64/libMagPlus.so"
    if lib is None:
      lib = "/home/makerpm/rpmbuild/BUILD/Magics-3.0.3-Source/build/lib/libMagPlus.so"
```

Right now we're shipping the rpm with tests disabled (even [official debian package has disabled tests](http://http.debian.net/debian/pool/main/m/magics++/magics++_3.0.2-1.debian.tar.xz) for different reasons)

**Comment by edigiacomo** [comment]
`Magics.py` is created at configure time from `Magics.py.in`:

```python
lib = ctypes.util.find_library("MagPlus")

if lib is None:                                                                 
    lib = "@CMAKE_INSTALL_PREFIX@/@INSTALL_LIB_DIR@/libMagPlus@CMAKE_SHARED_LIBRARY_SUFFIX@"
    if lib is None:                                                             
      lib = "@CMAKE_BINARY_DIR@/lib/libMagPlus@CMAKE_SHARED_LIBRARY_SUFFIX@"

dll  = ctypes.CDLL(lib)
```

Obviously, the nested `if lib is None` will never be reached.

Moreover, [`LD_LIBRARY_PATH` is used from Python >= 3.6][1] and (quote) *if a library cannot be found by any other means*: then, `/usr/lib64/libMagPlus.so` cannot be overwritten and, if it exists, the tests will use the installed library instead of the compiled one.

Note: we are not alone (from `python3-magics++_3.0.2-1_amd64.deb`):

```python
lib = ctypes.util.find_library("MagPlus")

if lib is None:
    lib = "/usr/lib/libMagPlus.so"
    if lib is None:
      lib = "/build/magics++-3.0.2/debian/build-py3/lib/libMagPlus.so"

dll  = ctypes.CDLL(lib)
```

[1]: https://docs.python.org/3/library/ctypes.html?highlight=ctypes#finding-shared-libraries

**Comment by edigiacomo** [comment]
I opened an issue in ECMWF bug tracker https://software.ecmwf.int/issues/browse/SUP-2455
