### ISSUE TITLE
magics::GribRotatedInterpretor::interpretAsMatrix raises (another) runtime error when _GLIBCXX_ASSERTIONS is set

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/Magics-rpm#19]
Similar to issue #18 but the runtime error in raised in another part of the function
 
```
/usr/include/c++/12/bits/stl_vector.h:1206: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::front() [with _Tp = double; _Alloc = std::allocator<double>; reference = double&]: Assertion '!this->empty()' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff788ebec in __pthread_kill_implementation () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff788ebec in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007ffff783e956 in raise () at /lib64/libc.so.6
#2  0x00007ffff78287f4 in abort () at /lib64/libc.so.6
#3  0x00007fffe94d7da0 in __gnu_debug::_Safe_sequence_base::_M_get_mutex() () at /lib64/libstdc++.so.6
#4  0x00007fffe4103689 in std::vector<double, std::allocator<double> >::front() [clone .part.0] [clone .lto_priv.0] (this=<optimized out>, this=<optimized out>) at /usr/include/c++/12/bits/stl_vector.h:1206
#5  0x00007fffe42bd728 in std::vector<double, std::allocator<double> >::front() (this=<optimized out>, this=<optimized out>) at /usr/include/c++/12/bits/stl_iterator.h:1072
#6  magics::GribRegularInterpretor::interpretAsMatrix(magics::GribDecoder&) const (this=<optimized out>, grib=<optimized out>)
    at /usr/src/debug/Magics-4.11.0-6.fc36.x86_64/src/decoders/GribRegularInterpretor.cc:569
...
(gdb) l src/decoders/GribRegularInterpretor.cc:569
564	        // instead of rows, so we have to 'reshape' the array so that it is
565	        // reorganised into rows.
566	
567	        if (jPointsAreConsecutive) {
568	            vector<double>* d = new vector<double>(nb);  // temporary array
569	            double* d1        = &d->front();             // temporary array pointer
570	            double* d2        = &u->front();             // final array
571	
572	            grib_get_double_array(grib.id(), "values", d1, &aux);
```

**Comment by edigiacomo** [comment]
Fixed in e29a38c04dc188fe86b93b3d93ad0061e6f8dc35
